/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ScoutingResult,
} from '../models';
import {
    ScoutingResultFromJSON,
    ScoutingResultToJSON,
} from '../models';

export interface ScoutGetRequest {
    users?: Array<string> | null;
    tiers?: Array<string> | null;
    opponents?: Array<string> | null;
    links?: Array<string> | null;
}

/**
 * 
 */
export class ScoutApi extends runtime.BaseAPI {

    /**
     */
    async scoutGetRaw(requestParameters: ScoutGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScoutingResult>> {
        const queryParameters: any = {};

        if (requestParameters.users) {
            queryParameters['Users'] = requestParameters.users;
        }

        if (requestParameters.tiers) {
            queryParameters['Tiers'] = requestParameters.tiers;
        }

        if (requestParameters.opponents) {
            queryParameters['Opponents'] = requestParameters.opponents;
        }

        if (requestParameters.links) {
            queryParameters['Links'] = requestParameters.links;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Scout`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScoutingResultFromJSON(jsonValue));
    }

    /**
     */
    async scoutGet(requestParameters: ScoutGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScoutingResult> {
        const response = await this.scoutGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
