/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTags: typeof import('bootstrap-vue-next')['BFormTags']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    CombosStatistics: typeof import('./components/Statistics/CombosStatistics.vue')['default']
    IBiCheck2: typeof import('~icons/bi/check2')['default']
    IBiCircleHalf: typeof import('~icons/bi/circle-half')['default']
    IBiGithub: typeof import('~icons/bi/github')['default']
    IBiMoonStarsFill: typeof import('~icons/bi/moon-stars-fill')['default']
    IBiPaypal: typeof import('~icons/bi/paypal')['default']
    IBiSunFill: typeof import('~icons/bi/sun-fill')['default']
    IBiTwitter: typeof import('~icons/bi/twitter')['default']
    IBiYoutube: typeof import('~icons/bi/youtube')['default']
    IconRenderer: typeof import('./components/Visuals/IconRenderer.vue')['default']
    ItemStatistics: typeof import('./components/Statistics/ItemStatistics.vue')['default']
    MonTable: typeof import('./components/Visuals/MonTable.vue')['default']
    MoveStatistics: typeof import('./components/Statistics/MoveStatistics.vue')['default']
    NavbarHeader: typeof import('./components/NavbarHeader.vue')['default']
    PokemonStatistics: typeof import('./components/Statistics/PokemonStatistics.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RepresentationsRenderer: typeof import('./components/RepresentationsRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScouterSearchMask: typeof import('./components/ScouterSearchMask.vue')['default']
    SearchQuery: typeof import('./components/Visuals/SearchQuery.vue')['default']
    SpritesRenderer: typeof import('./components/Visuals/SpritesRenderer.vue')['default']
    TableRepresentation: typeof import('./components/Representation/TableRepresentation.vue')['default']
    TextRepresentation: typeof import('./components/Representation/TextRepresentation.vue')['default']
    TournamentSearchMask: typeof import('./components/TournamentSearchMask.vue')['default']
    VisualRepresentation: typeof import('./components/Representation/VisualRepresentation.vue')['default']
  }
}
