// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTags: typeof import('bootstrap-vue-next')['BFormTags']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    IBiCheck2: typeof import('~icons/bi/check2')['default']
    IBiCircleHalf: typeof import('~icons/bi/circle-half')['default']
    IBiGithub: typeof import('~icons/bi/github')['default']
    IBiMoonStarsFill: typeof import('~icons/bi/moon-stars-fill')['default']
    IBiSunFill: typeof import('~icons/bi/sun-fill')['default']
    IBiTwitter: typeof import('~icons/bi/twitter')['default']
    IBiYoutube: typeof import('~icons/bi/youtube')['default']
    ItemStatistics: typeof import('./components/Representation/ItemStatistics.vue')['default']
    MonRenderer: typeof import('./components/MonRenderer.vue')['default']
    MonTable: typeof import('./components/MonTable.vue')['default']
    MoveStatistics: typeof import('./components/Representation/MoveStatistics.vue')['default']
    NavbarHeader: typeof import('./components/NavbarHeader.vue')['default']
    PokemonStatistics: typeof import('./components/Representation/PokemonStatistics.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMask: typeof import('./components/SearchMask.vue')['default']
    SearchUI: typeof import('./components/SearchUI.vue')['default']
    Statistics: typeof import('./components/Representation/Statistics.vue')['default']
    StatisticsTable: typeof import('./components/Representation/StatisticsTable.vue')['default']
    TextRepresentation: typeof import('./components/Representation/TextRepresentation.vue')['default']
  }
}
