/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiScoutingRequestAllOf
 */
export interface ApiScoutingRequestAllOf {
    /**
     * 
     * @type {boolean}
     * @memberof ApiScoutingRequestAllOf
     */
    provideOutput?: boolean | null;
}

/**
 * Check if a given object implements the ApiScoutingRequestAllOf interface.
 */
export function instanceOfApiScoutingRequestAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiScoutingRequestAllOfFromJSON(json: any): ApiScoutingRequestAllOf {
    return ApiScoutingRequestAllOfFromJSONTyped(json, false);
}

export function ApiScoutingRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiScoutingRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provideOutput': !exists(json, 'provideOutput') ? undefined : json['provideOutput'],
    };
}

export function ApiScoutingRequestAllOfToJSON(value?: ApiScoutingRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provideOutput': value.provideOutput,
    };
}

