/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OutputObject } from './OutputObject';
import {
    OutputObjectFromJSON,
    OutputObjectFromJSONTyped,
    OutputObjectToJSON,
} from './OutputObject';

/**
 * 
 * @export
 * @interface ApiScoutingResultAllOf
 */
export interface ApiScoutingResultAllOf {
    /**
     * 
     * @type {OutputObject}
     * @memberof ApiScoutingResultAllOf
     */
    outputs?: OutputObject | null;
}

/**
 * Check if a given object implements the ApiScoutingResultAllOf interface.
 */
export function instanceOfApiScoutingResultAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiScoutingResultAllOfFromJSON(json: any): ApiScoutingResultAllOf {
    return ApiScoutingResultAllOfFromJSONTyped(json, false);
}

export function ApiScoutingResultAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiScoutingResultAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'outputs': !exists(json, 'outputs') ? undefined : OutputObjectFromJSON(json['outputs']),
    };
}

export function ApiScoutingResultAllOfToJSON(value?: ApiScoutingResultAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'outputs': OutputObjectToJSON(value.outputs),
    };
}

