/* tslint:disable */
/* eslint-disable */
/**
 * Showdown Replay Scouter
 * This is the Showdown Replay Scouter API. <a href=\'https://github.com/FullLifeGames/Showdown-Replay-Scouter\'>This is the code.</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutputObject
 */
export interface OutputObject {
    /**
     * 
     * @type {string}
     * @memberof OutputObject
     */
    header?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OutputObject
     */
    teams?: Array<string>;
}

/**
 * Check if a given object implements the OutputObject interface.
 */
export function instanceOfOutputObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OutputObjectFromJSON(json: any): OutputObject {
    return OutputObjectFromJSONTyped(json, false);
}

export function OutputObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': !exists(json, 'header') ? undefined : json['header'],
        'teams': !exists(json, 'teams') ? undefined : json['teams'],
    };
}

export function OutputObjectToJSON(value?: OutputObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': value.header,
        'teams': value.teams,
    };
}

