/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerInfo
 */
export interface PlayerInfo {
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    playerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    playerValue?: string;
}

/**
 * Check if a given object implements the PlayerInfo interface.
 */
export function instanceOfPlayerInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PlayerInfoFromJSON(json: any): PlayerInfo {
    return PlayerInfoFromJSONTyped(json, false);
}

export function PlayerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'playerName': !exists(json, 'playerName') ? undefined : json['playerName'],
        'playerValue': !exists(json, 'playerValue') ? undefined : json['playerValue'],
    };
}

export function PlayerInfoToJSON(value?: PlayerInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'playerName': value.playerName,
        'playerValue': value.playerValue,
    };
}

