/* tslint:disable */
/* eslint-disable */
/**
 * Showdown Replay Scouter
 * This is the Showdown Replay Scouter API. <a href=\'https://github.com/FullLifeGames/Showdown-Replay-Scouter\'>This is the code.</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    PlayerInfo,
    instanceOfPlayerInfo,
    PlayerInfoFromJSON,
    PlayerInfoFromJSONTyped,
    PlayerInfoToJSON,
} from './PlayerInfo';

/**
 * @type ReplayPlayerInfo
 * 
 * @export
 */
export type ReplayPlayerInfo = PlayerInfo;

export function ReplayPlayerInfoFromJSON(json: any): ReplayPlayerInfo {
    return ReplayPlayerInfoFromJSONTyped(json, false);
}

export function ReplayPlayerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayPlayerInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...PlayerInfoFromJSONTyped(json, true) };
}

export function ReplayPlayerInfoToJSON(value?: ReplayPlayerInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfPlayerInfo(value)) {
        return PlayerInfoToJSON(value as PlayerInfo);
    }

    return {};
}

